### ISSUE TITLE
an issues

### ISSUE THREAD

**Issue by realclone1** [kijai/ComfyUI-OpenDiTWrapper#3]
Traceback (most recent call last):
  File "E:\Blender_ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\Blender_ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\Blender_ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-OpenDiTWrapper\nodes.py", line 133, in loadmodel
    OpenSoraVAE_V1_2(
  File "E:\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-OpenDiTWrapper\opendit\models\opensora\vae.py", line 762, in OpenSoraVAE_V1_2
    model = VideoAutoencoderPipeline.from_pretrained(from_pretrained, **kwargs)
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 3158, in from_pretrained
    config, model_kwargs = cls.config_class.from_pretrained(
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 603, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 632, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\configuration_utils.py", line 689, in _get_config_dict
    resolved_config_file = cached_file(
  File "E:\Blender_ComfyUI\python_embeded\lib\site-packages\transformers\utils\hub.py", line 442, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like hpcai-tech/OpenSora-VAE-v1.2 is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

I confirmed that I have put model.safetensors and config.json into models\opensora\OpenSora-VAE-v1.2

**Comment by cheezecrisp** [comment]
It's strange that the VAE model is not located in comfyui path, but in the disk C
My path is C:\Users\cheezecrisp\.cache\huggingface\hub\models--hpcai-tech--OpenSora-VAE-v1.2\snapshots\33d153e9b5a9f771a8a84f98bd3f46458a8ed0bf
